<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <RootNamespace>KnightBus.NewRelicMiddleware</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>NewRelic.Agent.Api for KnightBus</Description>
    <Version>13.1.0$(VersionSuffix)</Version>
    <PackageTags>knightbus;apm;newrelic.agent.api</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NewRelic.Agent.Api" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KnightBus.Core\KnightBus.Core.csproj" />
  </ItemGroup>
</Project>
