<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Redis Transport Management for KnightBus</Description>
    <Version>3.1.0$(VersionSuffix)</Version>
    <PackageTags>knightbus;redis;queues;messaging</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\knightbus\src\KnightBus.Core.Management\KnightBus.Core.Management.csproj" />
    <ProjectReference Include="..\KnightBus.Redis\KnightBus.Redis.csproj" />
  </ItemGroup>
</Project>
