version: 2.0.{build}

image: Visual Studio 2019

services: 
- mssql2017
- docker

build_script:
- cmd: >-
    dotnet build KnightBus.sln --configuration Release

before_test:
- docker pull redis
- docker run -d -p 6379:6379 --name redis6379 redis

test_script:
- cmd: >-
    dotnet test knightbus/tests/KnightBus.Core.Tests.Unit/KnightBus.Core.Tests.Unit.csproj --logger:Appveyor

    dotnet test knightbus/tests/KnightBus.Host.Tests.Unit/KnightBus.Host.Tests.Unit.csproj --logger:Appveyor

    dotnet test knightbus-azurestorage/tests/KnightBus.Azure.Storage.Tests.Unit/KnightBus.Azure.Storage.Tests.Unit.csproj --logger:Appveyor

    dotnet test knightbus-azureservicebus/tests/KnightBus.Azure.ServiceBus.Unit/KnightBus.Azure.ServiceBus.Unit.csproj --logger:Appveyor

    dotnet test knightbus-sqlserver/tests/KnightBus.SqlServer.Tests.Integration/KnightBus.SqlServer.Tests.Integration.csproj --logger:Appveyor
    
    dotnet test knightbus-schedule/tests/KnightBus.Schedule.Tests.Unit/KnightBus.Schedule.Tests.Unit.csproj --logger:Appveyor

    dotnet test knightbus-redis/tests/KnightBus.Redis.Tests.Unit/KnightBus.Redis.Tests.Unit.csproj --logger:Appveyor

    dotnet test knightbus-redis/tests/KnightBus.Redis.Tests.Integration/KnightBus.Redis.Tests.Integration.csproj --logger:Appveyor

artifacts:
- path: '**\bin\Release\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: 6j0rknpSgf32isfJIphnVch605uOxltQpriViVSnuEdjTzAdUvNRMe3jmNiw8l5p
  on:
    branch: master