version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: dotnet build --configuration Release
test_script:
- cmd: >-
    dotnet test tests/KnightBus.Core.Tests.Unit/KnightBus.Core.Tests.Unit.csproj --logger:Appveyor

    dotnet test tests/KnightBus.Host.Tests.Unit/KnightBus.Host.Tests.Unit.csproj --logger:Appveyor
artifacts:
- path: '**\bin\Release\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: Y4Xs2fUHf8VLuWaLjv994vLx3qQZ1qAiFW7NKfg7wuq7OtmOWCpVgzYACiXN1x/s
  on:
    branch: master