version: 2.0.{build}

image: Visual Studio 2022

services: 
- docker

init:
- net start MSSQL$SQL2019

build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start

    dotnet build KnightBus.sln --configuration Release

before_test:
- docker pull redis
- docker run -d -p 6379:6379 --name redis6379 redis

test_script:
- cmd: >-
    dotnet test knightbus/tests/KnightBus.Core.Tests.Unit/KnightBus.Core.Tests.Unit.csproj --logger:Appveyor

    dotnet test knightbus/tests/KnightBus.Host.Tests.Unit/KnightBus.Host.Tests.Unit.csproj --logger:Appveyor

    dotnet test knightbus-azurestorage/tests/KnightBus.Azure.Storage.Tests.Unit/KnightBus.Azure.Storage.Tests.Unit.csproj --logger:Appveyor
    
    dotnet test knightbus-azurestorage/tests/KnightBus.Azure.Storage.Tests.Integration/KnightBus.Azure.Storage.Tests.Integration.csproj --logger:Appveyor

    dotnet test knightbus-sqlserver/tests/KnightBus.SqlServer.Tests.Integration/KnightBus.SqlServer.Tests.Integration.csproj --logger:Appveyor
    
    dotnet test knightbus-schedule/tests/KnightBus.Schedule.Tests.Unit/KnightBus.Schedule.Tests.Unit.csproj --logger:Appveyor

    dotnet test knightbus-redis/tests/KnightBus.Redis.Tests.Unit/KnightBus.Redis.Tests.Unit.csproj --logger:Appveyor

    dotnet test knightbus-redis/tests/KnightBus.Redis.Tests.Integration/KnightBus.Redis.Tests.Integration.csproj --logger:Appveyor
    
    dotnet test knightbus/tests/KnightBus.DependencyInjection.Tests.Unit/KnightBus.DependencyInjection.Tests.Unit.csproj --logger:Appveyor

artifacts:
- path: '**\bin\Release\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: KIUXgE0m/ydtX5auUeaxv6BfLMMNT2L38dhaEkSsVEankUqrHMpaCDOODMHuP36T
  on:
    branch: master
