#!/bin/sh
# This script finds the files that are about to be committed,
# and runs dotnet format on them before adding them back to staging
FILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs")
[ -z "$FILES" ] && exit 0
echo "Running dotnet format for $FILES"
dotnet format --include $FILES

# Add back the modified files to staging
echo "$FILES" | xargs git add
echo "dotnet format done"
