<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Json.Net serialization for KnightBus</Description>
    <Version>5.1.0$(VersionSuffix)</Version>
    <PackageTags>knightbus;json.net;newtonsoft</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KnightBus.Messages\KnightBus.Messages.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
</Project>
