<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Shared core management functionallity for the KnightBus framework</Description>
    <Version>18.3.0$(VersionSuffix)</Version>
    <PackageTags>knightbus;servicebus;esb;queues;messaging</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KnightBus.Core\KnightBus.Core.csproj" />
  </ItemGroup>
</Project>
