<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>PostgreSQL Transport for KnightBus</Description>
    <Version>4.1.0$(VersionSuffix)</Version>
    <PackageTags>knightbus;postgresql;queues;messaging</PackageTags>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KnightBus.Core\KnightBus.Core.csproj" />
    <ProjectReference Include="..\KnightBus.PostgreSql.Messages\KnightBus.PostgreSql.Messages.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.DependencyInjection" />
  </ItemGroup>
</Project>
