<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\KnightBus.Newtonsoft\KnightBus.Newtonsoft.csproj" />
    <ProjectReference Include="..\..\src\KnightBus.Schedule\KnightBus.Schedule.csproj" />
    <ProjectReference Include="..\..\src\KnightBus.Core\KnightBus.Core.csproj" />
  </ItemGroup>
</Project>
