<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Azure Service Bus Transport Management for KnightBus</Description>
    <Version>4.2.0$(VersionSuffix)</Version>
    <PackageTags>knightbus;azure servicebus;amqp;queues;messaging</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KnightBus.Core.Management\KnightBus.Core.Management.csproj" />
    <ProjectReference Include="..\KnightBus.Azure.ServiceBus\KnightBus.Azure.ServiceBus.csproj" />
  </ItemGroup>
</Project>
