<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Moq" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\KnightBus.Host\KnightBus.Host.csproj" />
    <ProjectReference Include="..\..\src\KnightBus.Schedule\KnightBus.Schedule.csproj" />
  </ItemGroup>
</Project>
