<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Extension methods for setting up the KnightBus PostgreSql transport in Azure</Description>
    <Version>3.1.0$(VersionSuffix)</Version>
    <PackageTags>knightbus;postgresql;queues;messaging</PackageTags>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KnightBus.PostgreSql.Management\KnightBus.PostgreSql.Management.csproj" />
    <ProjectReference Include="..\KnightBus.PostgreSql.Extensions.Azure\KnightBus.PostgreSql.Extensions.Azure.csproj" />
  </ItemGroup>
</Project>
